function result = the1_convolution(image, filter)

% This function convolves an image with the given filter.

height = size(image, 1);
width = size(image, 2);
filter_size = size(filter);
result = zeros(height, width, 'uint8');

% Cast both parameters to signed int to avoid computation errors with
% negative intermediate results.
filter = double(filter);
image = double(image);

if filter_size == 3
    for y = 1:height
        for x = 1:width
            % Special cases needed for y=1, y=height, x=1, x=width since 
            % filter will try to include out of border pixels.
            
            if y == 1 % Upper side 
                if x == 1 % Upper left corner
                    new_pixel = image(y, x)     * filter(1,1) + ...
                                image(y, x)     * filter(1,2) + ...
                                image(y, x+1)   * filter(1,3) + ...
                                image(y, x)     * filter(2,1) + ...
                                image(y, x)     * filter(2,2) + ...
                                image(y, x+1)   * filter(2,3) + ...
                                image(y+1, x)   * filter(3,1) + ...
                                image(y+1, x)   * filter(3,2) + ...
                                image(y+1, x+1) * filter(3,3);
                elseif x == width % Upper right corner
                    new_pixel = image(y, x-1)   * filter(1,1) + ...
                                image(y, x)     * filter(1,2) + ...
                                image(y, x)     * filter(1,3) + ...
                                image(y, x-1)   * filter(2,1) + ...
                                image(y, x)     * filter(2,2) + ...
                                image(y, x)     * filter(2,3) + ...
                                image(y+1, x-1) * filter(3,1) + ...
                                image(y+1, x)   * filter(3,2) + ...
                                image(y+1, x)   * filter(3,3);
                else
                    new_pixel = image(y, x-1)   * filter(1,1) + ...
                                image(y, x)     * filter(1,2) + ...
                                image(y, x+1)   * filter(1,3) + ...
                                image(y, x-1)   * filter(2,1) + ...
                                image(y, x)     * filter(2,2) + ...
                                image(y, x+1)   * filter(2,3) + ...
                                image(y+1, x-1) * filter(3,1) + ...
                                image(y+1, x)   * filter(3,2) + ...
                                image(y+1, x+1) * filter(3,3);
                    
                end
            elseif y == height % Bottom side
                if x == 1 % Bottom left corner
                    new_pixel = image(y-1, x)   * filter(1,1) + ...
                                image(y-1, x)   * filter(1,2) + ...
                                image(y-1, x+1) * filter(1,3) + ...
                                image(y, x)     * filter(2,1) + ...
                                image(y, x)     * filter(2,2) + ...
                                image(y, x+1)   * filter(2,3) + ...
                                image(y, x)     * filter(3,1) + ...
                                image(y, x)     * filter(3,2) + ...
                                image(y, x+1)   * filter(3,3);
                elseif x == width % Bottom right corner
                    new_pixel = image(y-1, x-1) * filter(1,1) + ...
                                image(y-1, x)   * filter(1,2) + ...
                                image(y-1, x)   * filter(1,3) + ...
                                image(y, x-1)   * filter(2,1) + ...
                                image(y, x)     * filter(2,2) + ...
                                image(y, x)     * filter(2,3) + ...
                                image(y, x-1)   * filter(3,1) + ...
                                image(y, x)     * filter(3,2) + ...
                                image(y, x)     * filter(3,3);
                else
                    new_pixel = image(y-1, x-1) * filter(1,1) + ...
                                image(y-1, x)   * filter(1,2) + ...
                                image(y-1, x+1) * filter(1,3) + ...
                                image(y, x-1)   * filter(2,1) + ...
                                image(y, x)     * filter(2,2) + ...
                                image(y, x+1)   * filter(2,3) + ...
                                image(y, x-1)   * filter(3,1) + ...
                                image(y, x)     * filter(3,2) + ...
                                image(y, x+1)   * filter(3,3);
                end
            elseif x == 1 % Left side
                new_pixel = image(y-1, x)   * filter(1,1) + ...
                            image(y-1, x)   * filter(1,2) + ...
                            image(y-1, x+1) * filter(1,3) + ...
                            image(y, x)     * filter(2,1) + ...
                            image(y, x)     * filter(2,2) + ...
                            image(y, x+1)   * filter(2,3) + ...
                            image(y+1, x)   * filter(3,1) + ...
                            image(y+1, x)   * filter(3,2) + ...
                            image(y+1, x+1) * filter(3,3);
            elseif x == width % Right side
                new_pixel = image(y-1, x-1) * filter(1,1) + ...
                            image(y-1, x)   * filter(1,2) + ...
                            image(y-1, x)   * filter(1,3) + ...
                            image(y, x-1)   * filter(2,1) + ...
                            image(y, x)     * filter(2,2) + ...
                            image(y, x)     * filter(2,3) + ...
                            image(y+1, x-1) * filter(3,1) + ...
                            image(y+1, x)   * filter(3,2) + ...
                            image(y+1, x)   * filter(3,3);
                
            else % Not on borders
                new_pixel = image(y-1, x-1) * filter(1,1) + ...
                    image(y-1, x)   * filter(1,2) + ...
                    image(y-1, x+1) * filter(1,3) + ...
                    image(y, x-1)   * filter(2,1) + ...
                    image(y, x)     * filter(2,2) + ...
                    image(y, x+1)   * filter(2,3) + ...
                    image(y+1, x-1) * filter(3,1) + ...
                    image(y+1, x)   * filter(3,2) + ...
                    image(y+1, x+1) * filter(3,3);   
                
            end
            result(y, x) = new_pixel;
        end
    end
    
elseif filter_size == 2
    
else
    error('Invalid filter size.');
end
